import {useEffect,useRef,useState} from 'react';
import type {Point} from '../types';
export default function Signal({points,onset=0.045,compact=false}:{points:Point[];onset?:number;compact?:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);const [paused,setPaused]=useState(false);const [seconds,setSeconds]=useState(5);const [scale,setScale]=useState(1);const [traces,setTraces]=useState(['filtered','envelope']);
 useEffect(()=>{if(paused || !canvas.current)return;const c=canvas.current;const rect=c.getBoundingClientRect();const dpr=window.devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');if(!ctx)return;ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#252126';ctx.lineWidth=1;for(let x=0;x<w;x+=w/10){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=h/6){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
 const end=points.at(-1)?.time_ms||0;const start=end-seconds*1000;const colors:Record<string,string>={raw:'#888b97',filtered:'#9471f4',rectified:'#52aa88',envelope:'#f63b49'};
 for(const trace of traces){ctx.strokeStyle=colors[trace];ctx.lineWidth=trace==='envelope'?2:1;ctx.beginPath();let begun=false;for(const p of points){if(p.time_ms<start)continue;const x=(p.time_ms-start)/(seconds*1000)*w;const v=p[trace as keyof Point]-(trace==='raw'?0.5:0);const y=h*0.65-v*h*2*scale;if(!begun){ctx.moveTo(x,y);begun=true;}else ctx.lineTo(x,y);}ctx.stroke();}ctx.setLineDash([5,5]);ctx.strokeStyle='#9a454a';ctx.beginPath();ctx.moveTo(0,h*0.65-onset*h*2*scale);ctx.lineTo(w,h*0.65-onset*h*2*scale);ctx.stroke();ctx.setLineDash([]);
 },[points,paused,seconds,scale,traces,onset]);
 return <div className={'signal '+(compact?'compact':'')}><div className="section-title"><span>LIVE SIGNAL <small>Native DSP · {seconds}s window</small></span><button onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button></div><canvas ref={canvas} aria-label="Live signal waveform"/><div className="signal-controls">{['raw','filtered','rectified','envelope'].map(t=><label key={t}><input type="checkbox" checked={traces.includes(t)} onChange={()=>setTraces(traces.includes(t)?traces.filter(x=>x!==t):[...traces,t])}/>{t}</label>)}<select aria-label="Signal time window" value={seconds} onChange={e=>setSeconds(+e.target.value)}>{[2,5,10,15].map(s=><option key={s} value={s}>{s}s</option>)}</select><label>Scale <input aria-label="Signal scale" type="range" min="0.2" max="5" step="0.1" value={scale} onChange={e=>setScale(+e.target.value)}/></label></div></div>
}
