export interface Dsp {sample_rate:number;high_pass:number;low_pass:number;notch:number;envelope_ms:number;baseline_ms:number;onset:number;release:number;min_ms:number;max_ms:number;cooldown_ms:number}
export interface Example {id:string;captured_ms:number;duration_ms:number;peak:number;rms:number;shape:number[];waveform:number[];variant:string;negative:boolean;score:number}
export interface Profile {id:string;name:string;description:string;notes:string;color:string;created_at:number;updated_at:number;enabled:boolean;dsp:Dsp;sensitivity:number;threshold:number;ambiguity:number;cooldown_ms:number;min_ms:number;max_ms:number;mode:'Discrete'|'Hold'|'Continuous';examples:Example[];validation:{detected:number;missed:number;false_triggers:number;latency_sum_ms:number}}
export interface GraphNode {id:string;kind:string;label:string;x:number;y:number;params:Record<string,unknown>}
export interface GraphEdge {id:string;source:string;target:string;port:string}
export interface Graph {nodes:GraphNode[];edges:GraphEdge[]}
export interface NodePosition {id:string;x:number;y:number}
export interface Workspace {version:number;graph:Graph;profiles:Profile[];dsp:Dsp}
export interface Point {time_ms:number;raw:number;filtered:number;rectified:number;envelope:number}
export interface Snapshot {mode:string;device:string;source:string;firmware:number;protocol:number;rate:number;samples:number;dropped:number;corrupt:number;leads:number;adc:number;noise:number;envelope:number;ready:boolean;points:Point[];training:{profile_id:string|null;stage:string;accepted:number;rejected:number;candidate:Example|null;capture:Point[];variant:string;score:number};scores:[string,number][];last_match:string;recognition_status?:string;traces:{time_ms:number;node:string;kind:string;result:string}[];error:string;recording:number|null;diagnostics:Record<string,unknown>}
export const categories:Record<string,string[]>={Input:['Muscle Action'],Mouse:['Left Click','Right Click','Middle Click','Mouse Down','Mouse Up','Move Mouse','Scroll Vertical','Scroll Horizontal'],Keyboard:['Key Press','Key Down','Key Up','Shortcut','Type Text'],System:['Launch Application','Open File','Open Folder','Open URL','Approved Command'],Media:['Play/Pause','Next Track','Previous Track','Volume Up','Volume Down','Mute'],Timing:['Delay','Timer','Interval','Debounce','Cooldown','Pulse','Hold','Repeat'],Logic:['AND','OR','NOT','Gate','Toggle','Latch','Counter','Compare','Branch','Debug']};
